### ISSUE TITLE
Crash when drawing selection box

### ISSUE THREAD

**Issue by MorayM** [trigger-segfault/OpenLRR#62] opened 2023-03-22 11:40 UTC
**Describe the issue**
Occasionally when clicking and holding to draw a selection box, the game freezes with the following message being continuously generated in the console until the it is killed:

```
C:\OpenLRR\src\openlrr\engine\drawing\Draw.cpp(146): Warning: Draw_End: Called without first calling Draw_Begin()
C:\OpenLRR\src\openlrr\engine\drawing\Draw.cpp(194): Warning: Draw_SetTranslation: Called without first calling Draw_Begin()
```

The trigger appears to be on mousedown+drag event.

**Expected behaviour**
A selection box can be drawn as normal

**Steps to reproduce**
Appears to occur randomly.

**Additional information**
* **Time played this session:** Any time
* **Level:** Lava Laughter and Oresome but may be more
* **Game speed:** 100%
* **Graphics fix:** dgVoodoo
* **Using mods:** None

***

**Additional context (optional)**

**Screenshots (optional)**

**Comment by RingtailRaider** [comment] 2023-06-03 02:24
what version of dgvoodoo?

**Comment by MorayM** [comment] 2023-06-05 09:41
2.79.3

**Comment by RingtailRaider** [comment] 2023-06-06 03:30
okay, just wanted to make sure since versions before that one had issues with LRR, and there was a specific issue with drawboxes freezing game back in like 2.54 or something.

**Comment by trigger-segfault** [comment] 2023-06-17 19:34
What's strange is this issue may be caused by the selection box, but the warning messages you're seeing are caused by some other drawing action, like the Radar Map, or unit Health Bars, as there aren't many cases where the Translation function is used. My only guess on what's happening is that the surface locking happening in the drawing API is failing after some behaviour caused by the drag selection boxes.

I added logging messages awhile ago to see where failure is occurring and they can be tested by using any of the nightly builds that are generated by each commit on GitHub.

Here's a link to the latest nightly build as of making this comment (note these nightly builds will expire 90 days after the commit. I plan on finding some method to permanently store these builds eventually.)

[Nightly build](https://github.com/trigger-segfault/OpenLRR/actions/runs/5299431439) - [Direct Download](https://github.com/trigger-segfault/OpenLRR/suites/13678200471/artifacts/755827119)

**Comment by MorayM** [comment] 2023-07-20 15:27
I've been playing with the build from https://github.com/trigger-segfault/OpenLRR/commit/9ec34ee254d3c1846cc41a348e160dc4fcfb966f and haven't been able to reproduce this issue - guess it was a side effect of something else. I did encounter an issue where all raiders on foot disappeared instantly, and any new raiders disappeared as soon as the teleport animation finished but I won't log that as a bug until I can reproduce it.

**Comment by trigger-segfault** [comment] 2023-07-20 20:16
Thanks for reporting back. I'm going to close this for now, and re-open it if the issue pops up again. :)

The other bug you mentioned is something I've been calling Void Routing / NaN Routing. It's caused when a unit tries to do/calculate something that's zero distance away and then requires a direction vector towards it, which causes a divide by zero. This already has an issue (#12).

**Closed by trigger-segfault** 2023-07-20 20:16 UTC
Labels: crash, graphics, investigate
