### ISSUE TITLE
Random landslide sounds and notifications at the start of levels

### ISSUE THREAD

**Issue by RingtailRaider** [trigger-segfault/OpenLRR#44] opened 2022-08-12 06:44 UTC
**Describe the issue**
Sometimes when starting the level, the sound of a wall collapsing will play, despite there being no collapsing wall nearby. Very rarely, Chief's landslide announcement will play as well, despite no landslide notification appearing.

When encountered in a level, it will always play at the start of the level no matter how many times the level is restarted. However, what levels it happens in, if any, seems random. It appears to function separately from #42.

It most commonly happens in Breathless, but has also been heard in Erode Works, Lake of Fire, Hot Stuff, and Rocky Horror. It does not seem to happen in levels that start with Chief announcing something.

**Steps to reproduce**
Unknown. It happens randomly, and Chief's landslide announcement is extremely rare.

**Additional information**
* **Time played this session:** Varies
* **Level:** Varies
* **Game speed:** 100%
* **Graphics fix:** dgVoodoo 2.79.1
* **Using mods:** None

Update: This is probably related to #42, since Driller Night and Explosive Action both also have a collapsing wall at the beginning of the level. I'm not going to close as duplicate until it's certain.

**Comment by trigger-segfault** [comment] 2022-08-16 18:33
This does indeed seem to be a duplicate of #42, and has been fixed with 219a66d8264acdfc47e474a4610ad9b35deb5093.

You can consistently reproduce the landslide issue by following the initial steps for reproduction in closed issue #3. Rubble Trouble has landslides that can always trigger on the first frame of the level if you get into the level fast and before triggering other RNG.

**Closed by trigger-segfault** 2022-08-16 18:33 UTC
Labels: bug, duplicate, audio
